### ISSUE TITLE
FR: Make Site variables available

### ISSUE THREAD

**Issue by awcodes** [edalzell/statamic-blade#14]
Trying to do 
```
@globalset('site', 'short_locale')
```
but getting the following error: 
```
Call to a member function inCurrentSite() on null
```

Am I doing something wrong or is the site global not available?

Thanks for the great addon.

**Comment by edalzell** [comment]
Is `site` an actual global? Like you created it?

**Comment by awcodes** [comment]
Site is a global provided in antlers. https://statamic.dev/variables/site

**Comment by edalzell** [comment]
Ah ya, that's not what this blade directive is for. This one is for actual GlobalSets, not global variables.

**Comment by edalzell** [comment]
there you go @awcodes, added a new `site` directive for you in the latest release.

**Comment by awcodes** [comment]
@edalzell Thank you so much. This is awesome. I really appreciate it.
