### ISSUE TITLE
Replicator directive?

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#17]
I am currently attempting to output replicator fields like so:

**post.blade.php:**
```
@foreach($replicatorField as $set)	
	@include("partials.statamic.sets.{$set['type']}", ['data' => Arr::except($set, 'type')])
@endforeach
```

**Hero set template example:**
```
{{ dd($data) }}
```

![image](https://user-images.githubusercontent.com/20210934/97787973-6607a000-1bad-11eb-8f26-7241d5520d0e.png)
Only the asset filename is available, and I don't see an easy way to access alt text or other image attributes. 

I'm having similar trouble with the Bard field. Ideally I would like to have access to all of the asset's data, or failing that, the asset id so that I can retrieve it manually.

**Comment by dubcanada** [comment]
If you do

```
@foreach($replicatorField->getValue() as $set)
	{{$set->url()}}
@endforeach
```

It will work.

**Comment by edalzell** [comment]
PRs gladly accepted @dubcanada

**Comment by stuartcusackie** [comment]
> ->getValue()

I'm afraid that doesn't work for my implementation:

```
PostController function:

return (new \Statamic\View\View)
	        ->template('posts.show')
	        ->cascadeContent($entry);

```

```
posts.show.blade.php

@foreach($replicator->getValue() as $set
```

```
Call to undefined method Statamic\Fields\Value::getValue() 
```

**Comment by dubcanada** [comment]
Just a random thought, but have you tried using the Bard directive with the Replicator data? I believe they way they are implemented is basically the same.

**Comment by stuartcusackie** [comment]
I believe I have. Not 100% sure but yeah, I think I tried that. It seems my custom implementation, show below, doesn't process the entire Entry object in the same way as Statamic's default routing would:

```
/**
     * Return a single article view
     * 
     * @param \Statamic\Entry $post
     * @return \Statamic\View\View
     */
public function show(Entry $post) {

        return (new \Statamic\View\View)
	        ->template('posts.show')
	        ->cascadeContent($entry);
}
```

**Comment by edalzell** [comment]
I got replicator going, will release this weekend.

**Comment by stuartcusackie** [comment]
I was using a custom routing / controller structure like so:

routes/web.php
```
Route::bind('postSlug', function ($value) {
	return Entry::findBySlug($value, 'posts');
});

Route::get('/blog/{postSlug}', ['as' => 'post.view', 'uses' => 'PostController@show']);
```

PostController.php
```
/**
 * Return a single article view
 * 
 * @param \Statamic\Entry $post
 * @return \Statamic\View\View
 */
public function show(Entry $post) {
    return (new \Statamic\View\View)
        ->template('posts.show')
        ->cascadeContent($entry);
}
```

**Comment by edalzell** [comment]
Why do it that way though @stuartcusackie? Make that route the collection route so Statamic will feed in the data for you?

**Comment by edalzell** [comment]
> I'm afraid that doesn't work for my implementation. I'm trying not to use Statamic's default routing and do it purely through Laravel's routing / controller system.

Why do it that way though @stuartcusackie? Make that route the collection route so Statamic will feed in the data for you?

If you absolutely **must** do it that way, you likely need an `@entry('collection-handle', 'the-slug')` directive right?

**Comment by edalzell** [comment]
@stuartcusackie come on the discord and let's talk about it...I'd like to get this sorted for folks like you

**Comment by stuartcusackie** [comment]
To me that's a pretty standard Laravel route / controller / view structure, and with it I don't have to worry about Statamic's routes conflicting with my pre-existing Laravel routes.  I would prefer to stick even closer to Laravel and pass the entry as standard blade data, e.g.:

```
return view('posts.show', ['entry' => $entry]);
```

but with that approach the full entry data doesn't become available to the view.

An @entry('collection-handle', 'the-slug') directive could solve it.

I joined the discord channel.

**Comment by edalzell** [comment]
Should be good to go now @stuartcusackie in v2.0.

**Comment by stuartcusackie** [comment]
Brilliant. Thank you.
