### ISSUE TITLE
Images within bard fieldsets don't get passed alt

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#18]
If I add an image directly to a bard field then I can see the alt text as part of the content, which is fine.

However, If I add an image to a field set within a bard field then only the image filename is available, which isn't very useful. 

Here is a screen shot of a 'hero' field set contained within my bard field:
![image](https://user-images.githubusercontent.com/20210934/97777643-8a418d80-1b69-11eb-8580-02ffc30bd8bb.png)

Ideally I would like to have access to all of the asset's / image's attributes.

Perhaps I am cascading the entry to my blade template incorrectly. Here is how I am doing that:

**routes/web.php**
```
Route::bind('postSlug', function ($value) {
    return \Statamic\Facades\Entry::findBySlug($value, 'posts');
});

Route::get('/blog/{postSlug}', ['as' => 'post.view', 'uses' => 'PostController@show']);
```

**PostController.php**
```
/**
* Return a single article view
* 
* @param \Statamic\Entry $post
* @return \Statamic\View\View
*/
public function show(Entry $post) {
    return (new \Statamic\View\View)
	    ->template('posts.show')
	    ->cascadeContent($post);
}
```

**Comment by edalzell** [comment]
@stuartcusackie these directives are meant to be used on their own, not with custom controllers.

**Comment by stuartcusackie** [comment]
Oh right. It seems I am going about this entirely the wrong way then.  I would have thought the Entry object would be compatible and fully accessible through any part of Laravel.

I'm fumbling my way round Statamic at the moment. There is literally no material available on custom integrations, but perhaps this is an issue for the Statamic core.

Thanks.

**Comment by edalzell** [comment]
> Oh right. It seems I am going about this entirely the wrong way then. I would have thought the Entry object would be compatible and fully accessible through any part of Laravel.

Ya that's not quite there yet @stuartcusackie, that's why I made my addon, to give Blade folks access to Statamic. Feel free to add FRs to the repo for bits you need to keep going. Believe there's one already for Entry and Taxonomy.
