### ISSUE TITLE
Please add phpunit.xml.dist

### ISSUE THREAD

**Issue by bakerkretzmar** [edalzell/statamic-blade#2]
Love this package, was literally searching for something just like it earlier this week!

Could you un-gitignore your `phpunit.xml`, or add a `phpunit.xml.dist`, so we can run the tests? Thanks!

**Comment by edalzell** [comment]
Tests definitely needs fleshing out, done in https://github.com/edalzell/statamic-blade/commit/d16f534856d6c31f0f74169c25e024284668e149
