### ISSUE TITLE
Add an Augment directive

### ISSUE THREAD

**Issue by FlorianMoser** [edalzell/statamic-blade#20]
Currently there is the `@data` directive to augment `$data->value()` fields. However, Statamic generates data without values. Take term entries, for example.

Term entry pages have a variable `$entries`, which is a `Statamic\Stache\Query\EntryQueryBuilder` object. Using `Statamic\Stache\Query\EntryQueryBuilder::get()` we get a `Statamic\Entries\EntryCollection` object, which needs augmentation. We can't use `@data` for this object, because there is no value() method.

Maybe clone the `Edalzell\Blade\Directives\Data` directive to something like `Edalzell\Blade\Directives\Augment` and remove the `->value()` part? With a `@augment` directive, we could then augment all kind of iterable data.

**Comment by edalzell** [comment]
I don't like my solution, but I made the `@data` tag a bit smarter so it'll work on `$entries` and other `Builder`s.

**Comment by FlorianMoser** [comment]
Nice!

Yeah, I know what you mean. But I see no other option at the moment.
