### ISSUE TITLE
IsDirective trait throwing an exception 

### ISSUE THREAD

**Issue by johncarter-** [edalzell/statamic-blade#21]
I am using this in my template
```blade
            @taxonomy('product_brand')
            @dump($term['logo'])
            @endtaxonomy
```
An exception is thrown which can be seen here: https://flareapp.io/share/Rmrg2lMP#F67

It actually throws this on any of the directives.

**Comment by edalzell** [comment]
@johncarter- can you throw a `dd($data);` in the line above that if statement and put the results here?

**Comment by johncarter-** [comment]
Sure, ill be a while though.

**Comment by johncarter-** [comment]
```
Statamic\Taxonomies\LocalizedTerm {#2384 ▼
  #locale: "default"
  #term: Statamic\Taxonomies\Term {#2336 ▼
    #taxonomy: "product_brand"
    #slug: "aigle"
    #blueprint: null
    #collection: null
    #data: Illuminate\Support\Collection {#2339 ▼
      #items: array:1 [▼
        "default" => Illuminate\Support\Collection {#2349 ▼
          #items: array:1 [▼
            "title" => "Aigle"
          ]
        }
      ]
    }
    #initialPath: "/var/www/html/content/taxonomies/product_brand/aigle.yaml"
  }
  #slug: null
  #published: true
  #selectedQueryColumns: null
}
```

**Comment by johncarter-** [comment]
Seems if I change the method to this it works:
```php
if (method_exists($data, 'toAugmentedArray')) {
    // return $this->getAugmentedValue($data->toAugmentedArray());
    return $data->toAugmentedArray();
}
```

**Comment by edalzell** [comment]
@johncarter- can you try with the latest version please?

**Comment by johncarter-** [comment]
Which latest version? 👀

**Comment by edalzell** [comment]
Like any normal package, `composer update`, or check here: https://github.com/edalzell/statamic-blade/releases

**Comment by johncarter-** [comment]
It was, and still is on v2.1.

composer.lock:

![image](https://user-images.githubusercontent.com/3776888/102774685-5aea1880-4383-11eb-9bc1-f3c2678e9066.png)

composer.json
![image](https://user-images.githubusercontent.com/3776888/102774718-72c19c80-4383-11eb-86ff-98c0e2cdd764.png)

**Comment by edalzell** [comment]
@johncarter- I have the same code in my test template:

```
@taxonomy('tags')
    <p>Title is {{ $term['title'] }}</p>
@endtaxonomy
```

And I don't have this error.

Hit me up on Discord sometime and we'll figure it out.

**Comment by canastro** [comment]
Im having the same error in a new project, even for the @collection component

**Comment by jakubjo** [comment]
I have the same error with the current version using the `@collection` directive.

**Comment by edalzell** [comment]
Alrighty, I'll take a look this weekend

**Comment by edalzell** [comment]
@canastro @jakubjo what are your steps for making this happen? I can't make this break. My steps:

* created a new Statamic site, then `composer required edalzell/blade-directives`
* Added a second page to the `pages` collection.
* made a `try-blade.blade.php` file with this in it:
```
@collection('pages')
    {{ $entry['title'] }}
@endcollection
```
* add a route in my `web.php`, `Route::view('/blade', 'try-blade');`
* visited `http://mysite.test/try-blade`

I see this:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/6069653/104818385-26c81300-57dc-11eb-9bb0-7d0568e84f7a.png">

What am I doing differently than you? cc @johncarter-

**Comment by jakubjo** [comment]
I had an existing Laravel website to which I added statamic. 

- Created a "pages" Collection with the page "blog" and a Blade template
- Tried @collection -- got the issue
- I use blade components for the layout

The view's code:

```blade
<x-app-layout>
    <x-slot name="header">
        <x-common-header title="{{ $title }}">
            {{ $teaser }}
        </x-common-header>
    </x-slot>

    <article>
        @collection('blog')
            {{ dd($entry) }}
        @endcollection
    </article>
</x-app-layout>
```

**Comment by edalzell** [comment]
@jakubjo would you be willing to send me (pro give me quick access to the repo) your site? Or at least enough of it to reproduce the issue?

erin@silentz.co

**Comment by jakubjo** [comment]
You seem a decent man. Let's try it out. There are some, hopefully, harmless secrets. Please delete the repo afterwards. You need to checkout the `statamic` branch.

**Comment by edalzell** [comment]
I can't find that code mentioned above, can you please let me know where it is? Perhaps come on the Statamic discord and PM me?

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
