### ISSUE TITLE
Replicator ordering not showing in live preview

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#26]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/20210934/108878083-c9ec2380-75f7-11eb-8b1c-39c28b236b6b.gif)

Not sure if this is a problem with this package or Statamic's core but I thought you might know better. Ordering works fine when viewing the front-end but not in Live Preview.

Let me know if you want me to add it to the main Statamic issues repo.

**Comment by edalzell** [comment]
You are using the blade directive in your view?

**Comment by stuartcusackie** [comment]
I think I am!

```
@entry('pages', $slug)
		@foreach($builder_replicator as $index => $set)
```

Also, the 'Included in output' toggle seems to have no effect either, but both of these features work on the front-end.

**Comment by stuartcusackie** [comment]
Duncan McClean has a theory about it: https://github.com/statamic/cms/issues/3297

**Comment by stuartcusackie** [comment]
I just figured out that this works:

```
@data($builder_replicator)
		@foreach($data as $index => $set)
```

So I don't need to use the entry directive it seems.
