### ISSUE TITLE
Question: How to use Glide?

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#28]
Any advice on the best way to handle assets and utilise Glide within blade? Will this package eventually have an @asset directive?

I found this on the Discord:
`<img src="{{ app(Statamic\Imaging\Manager::class)->manipulate($image['id'], ['w' => 700, 'fm' => 'png']) }}" />`

It seems to do the job, though I'm not sure if the url it produces is what I would get from Antlers:
`/img/asset/aW1hZ2VzL2V4YW1wbGUtdHJhbnNwYXJlbnQtMS5wbmc=?w=700&fm=jpg&s=5163d2335c3bd4318e3ab4cd6035597e`

I suppose I'll just stick this into a little helper file, but it would be good to know that I'm not going about this arseways.

**Comment by edalzell** [comment]
There's a glide directive:

```
@glide('/assets/IMG_1325.jpeg', ['width' => 100])
    <p>URL is {{ $url }}</p>
    <img src="{{ $url }}">
    <p>Width is {{ $width }}</p>
    <p>Hight is {{ $height }}</p>
@endglide
```

**Comment by stuartcusackie** [comment]
Fantastic. Thank you.

**Comment by MarlBurroW** [comment]
My way to use glide in statamic with blade:

Create a `helpers.php` in `app/` and autoload it:

`composer.json`
```json
{
"autoload": {
    "files": [
        "app/helpers.php"
    ],
}
```

`helpers.php`
```php
# helpers.php
<?php
function statamic_image($image, $params)
{
    if ($image instanceof Statamic\Fields\Value) {
        $image = $image->value();
    }

    if (!$image instanceof Statamic\Assets\Asset) {
        return null;
    }

    return app(Statamic\Contracts\Imaging\ImageManipulator::class)->item($image)->params($params)->build();
}

```

`In any *.blade.php`
```blade
   <img src="{{ statamic_image($image, ['w' => 1920, 'h' => 600]) }}">
```

Hope it may help
