### ISSUE TITLE
Feature request: Bard directive

### ISSUE THREAD

**Issue by bakerkretzmar** [edalzell/statamic-blade#3]
It would be awesome if this package allowed us to something like this, but with Blade (where `content` is a Bard field):

```blade
{{ content }}
    {{ partial src="sets/{type}" }}
{{ /content }}
```

I'm imagining the syntax being as simple as:

```blade
@bard('content')
```

and the partials for each set could be looked up in `partials/sets/` by default. Or that could be configured:

```blade
@bard('content', ['sets' => 'partials/my-subdirectory/sets'])
```

Could be neat to do 'dynamic' sets too, something like:

```blade
@bard('content')
    @set('text', 'partials/sets/text.blade.php')

    @set('one-off')
        <div>I'm special.</div>
    @endset
@endbard
```

**Comment by edalzell** [comment]
how does bard content show up...why do you need the directive? Isn't it in an array already?

Or do you want those directives to do that processing that Statamic does?

**Comment by bakerkretzmar** [comment]
The Bard content comes in as a `Statamic\Field\Value`, which you can get an array from but it's really weirdly structured, any text formatting like links, bold/italics, etc. is another nested array inside that part of the content. This might be less useful than I'm imagining but yeah, I'm basically thinking the directive would do what Statamic does now so I can mostly keep things structured how they are now and just use Blade instead of Antlers.

**Comment by edalzell** [comment]
@bakerkretzmar are you open to helping build this? I need you to try what I've got to see if it matches what you're trying to do.

**Comment by bakerkretzmar** [comment]
@edalzell yeah! I tried to get something working yesterday with a janky `@foreach` and `@switch` just in a template, to get a feel for how the Bard field is structured, but would love to see what you've come up with 😂

**Comment by edalzell** [comment]
What I've got so far
<img width="441" alt="image" src="https://user-images.githubusercontent.com/6069653/89742926-1eacc000-da53-11ea-93a2-6f335ab1d9f3.png">

**Comment by edalzell** [comment]
In 1.1
