### ISSUE TITLE
Ordered Collections not sorting properly

### ISSUE THREAD

**Issue by stuartpringle** [edalzell/statamic-blade#30]
I have a collection of team members on my site.  I've set the collection to 'Tree' (or, sortable) which gives me this in my .yaml file:

```
structure:
  root: false
  tree:
    -
      entry: 0b9f06a9-80bf-4c5d-a056-c31387156ffb
    -
      entry: f81b591b-7de7-493e-bb03-dace43cc321b
    -
      entry: 213ac6eb-f6e6-489d-9ea2-478bde112783
```

In my .blade.php template file, I'm using the following (with other html and such):
```
@collection('employees')
<h2>{{ $entry['title'] }}</h2>
@endcollection
```

This refuses to sort according to the tree noted above.  Instead, the default sort order is by title descending.

One of my employees' .md file:
```
---
title: 'Test'
image: team/team_members/test.jpg
position: Tester
updated_by: 6694d2a3-2507-4e08-bdd1-78c4014c99f6
updated_at: 1615343516
id: 0b9f06a9-80bf-4c5d-a056-c31387156ffb
---
```
Let me know if you need any more information.

**Comment by edalzell** [comment]
Should be fixed in v3.0
