### ISSUE TITLE
FR: Assets integration

### ISSUE THREAD

**Issue by robdekort** [edalzell/statamic-blade#34]
I love this Erin. Works really well and fluent thus far.

It would be nice if you could easily fetch asset metadata like `alt`, `focus` or `focus_css`.

**Comment by edalzell** [comment]
Can you show me how you want to use it (pseudo code is fine)?

**Comment by robdekort** [comment]
Probably combined with the `@glide` directive in _most_ cases:

```php
@asset($image)
    @glide($image, ['width' => 400])
        <img 
            src="{{ $url }}" 
            class="absolute inset-0 w-full h-full filter-grayscale opacity-70 object-cover" 
            style="object-position: {{ $focus_bg }}"
            alt="{{ $alt }}"
        />
    @endglide
@endasset
```

I'm really new to Blade so I'm not sure if something like this is conventional.

**Comment by edalzell** [comment]
Hey @robdekort `$image` there is the path right? We'd also need the container, right? I'm not sure that's avail by default in Blade views (like it would be in Antlers).

**Comment by robdekort** [comment]
Sorry for my super late response. I completely missed this. `$image` would indeed be the path, just like the [`asset` tag in Antlers](https://statamic.dev/tags/asset#content). We don't need to provide the container there. As a user I wouldn't expect you'd need to provide it in Blade. But maybe I'm misunderstanding?
