### ISSUE TITLE
FR: Determine if a collection is empty?

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#38]
What would be the most efficient way to determine that the collection is empty? 

```
@collection('blog', ['limit' => 12, 'sort' => 'created_at:desc'])
{{-- Output entry --}}
@endcollection
```

I would naturally try something like:
```
@collection('blog', ['limit' => 12, 'sort' => 'created_at:desc'])
{{-- Output entry --}}
**@elsecollection**
<p>No posts exists.</p>
@endcollection
```

But the [standard antler variables](https://statamic.dev/tags/collection#variables) would work too if they were accessible.

**Comment by edalzell** [comment]
That's a good feature request, thanks!

**Comment by stuartcusackie** [comment]
@edalzell  I think the no_results variable might be more flexible, and even better if the others variables would then be available too (e.g. total_results)?

@elsecollection might make sense too because I think Laravel uses similar things: @auth @elseauth @disk @elsedisk etc.
