### ISSUE TITLE
Does pagination work on collections?

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#39]
Is the standard collection pagination handled by this package?

I was trying this to no avail:

```
// limit to 1 to test pagination
@collection('blog', ['limit' => 1, 'sort' => 'created_at:desc', 'paginate' => true, 'as' => 'entries'])

  @foreach($entries as $entry)

    @data($entry)
      {{-- output entry --}}
    @enddata

  @endforeach 

@endcollection
```

**Comment by edalzell** [comment]
Don't think so, sorry.

I'll take a look at this in a bit.

**Comment by connor11528** [comment]
What is the livewire approach to pagination? I'd also like to be able to display multiple pages of results :)

**Comment by stuartcusackie** [comment]
> What is the livewire approach to pagination? I'd also like to be able to display multiple pages of results :)

Well, Livewire is a little more advanced if you haven't used [Laravel's basic pagination](https://laravel.com/docs/8.x/pagination) first. You can use this route / controller approach for Statamic as well.

The Statamic docs have the basics for routing mentioned [here](https://statamic.dev/controllers), but no examples of paginating entries in the controllers. Here's a example:

```
$articles = \Statamic\Facades\Entry::query()
            ->where('collection', 'articles')
            ->orderBy('created_at', 'desc')
            ->paginate(12);
```

For Livewire pagination, assuming you know how Livewire works, see [here](https://laravel-livewire.com/docs/2.x/pagination).

**Comment by connor11528** [comment]
Okay neat @stuartcusackie! I didn't realize I could call paginate and orderBy on the Entry collection like that. How awesome.

**Comment by edalzell** [comment]
@stuartcusackie got it working with the latest release, when I release try:

```
@collection('blog', ['limit' => 2, 'paginate' => true])
    @foreach($entry['entries'] as $entry)
        @data($entry)
            Title: {{ $title }}
        @enddata
    @endforeach
@endcollection
```
