### ISSUE TITLE
FR: @elsedata could be useful

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#40]
At the moment it's kind of confusing to see if a field is empty. This is what I'm trying to do:

```
@if($field)
    @data($field)
        {{-- do my thing with the field --}}
    @enddata
@else
@endif
```

However the @if statement passes, even when the field is empty. In fact, these both pass:
```
@if($field)
@if(isset($field))
```

So I find myself having to remember to do this:
`@if(isset($field) && is_array($field))
`

I was thinking that an **@elsedata** would solve this...?

**Comment by edalzell** [comment]
@stuartcusackie can you try the latest release w/ the augmentation? Does that solve this issue?

**Comment by stuartcusackie** [comment]
hmm, updating to 3.2 actually broke my site, without switching to the AugmentationViewServiceProvider:

`Cannot use object of type Statamic\Fields\LabeledValue as array`
 
Sorry, I may not have explained clearly. A lot of my code is based around \Statamic\Fields\Value objects and the way it was in 3.1 was totally fine, except for this particular small problem.

**Comment by edalzell** [comment]
@riasvdv see above.

@stuartcusackie sorry, I'll take a look this weekend, hopefully. Rollback to 3.1 in the meantime, of course.

**Comment by stuartcusackie** [comment]
@edalzell 

Cheers. I'm still testing here. I will update soon.

**Comment by stuartcusackie** [comment]
After more testing and a few tweaks to my code, 3.2 in general seems to work fine and it's easier to access fields. I don't think I will be using the AugmentationViewServiceProvider for the moment however.

The original problem I raised isn't really solved. I still have to do a second check to see if a field is empty:
`@if(isset($imageField) && $imageField->raw())`

Actually there is one thing broken for me now. I used to be able to do this in a custom controller for my articles index:

```
$viewData = array_merge([
  'articles' => $articles,
], $this->getAugmentedValue($page));
```

Which would provide all my entry fields to the view in the same way as the package does. Since updating to 3.2. it seems to have changed my fields from Arrays to Statamic\Fields\Values, which is breaking my logic. I'll keep testing next week.

**Comment by edalzell** [comment]
> So the original problem I raised still exists and I still have to do a second check to see if a field is empty:
> `@if(isset($imageField) && $imageField->raw())`

Ya that's an issue w/ Statamic's augmentation. Even null values are `Value`s. I've had to code around that in custom tags/modifiers.

Not sure the best way to handle.

**Comment by stuartcusackie** [comment]
That's fine. This is all relatively new to me and I'm confused. @elsedata stills seems like it would be a nice one though.

**Comment by edalzell** [comment]
@stuartcusackie what is `imageField` here?

**Comment by stuartcusackie** [comment]
@edalzell $imageField is just a regular single file asset field. It was just an example. In my project it is actually called **$open_graph_image**, which gets passed directly to the template as a Value object - I don't think I'm doing anything unusual here.

Here is my code. No directives have been used when the first @if statement is called, so that's why it's still a `Value`.

```
{{-- Can we eliminate the @if @else statements and get the directive to handle this logic? --}}
@if(isset($open_graph_image) && $open_graph_image->raw())
@data($open_graph_image)
	@glide(Storage::disk('public_images')->url($path), ['width' => 1200, 'height' => 627, 'fit' => 'crop_focal', 'fm' => 'jpg'])
	<meta property="og:image" content="{!! $url !!}" />
	@endglide
@enddata
@else
<meta property="og:image" content="{!! url('/images/default-og.jpg') !!}" />
@endif
```

Bear in mind that everything works fine. I just thought the directive could simplify the above.

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
