### ISSUE TITLE
[Question] How to check if a field is set or not ?

### ISSUE THREAD

**Issue by MarlBurroW** [edalzell/statamic-blade#47]
I want to display an optional image in my template, but I need to now if my image field is set or not.

So I tried somehting like this:
```blade
@if($image)
   @data($image)
        {{ $url }}
   @enddata
@endif
```
But it doesn't work because $image is always an instance of `Statamic\Fields\Value`, so never a falsy value.

Is there a better `statamic-blade` way to check if a field is set or not ? It's maybe more a Statamic related issue, I don't know.

Thanks

**Comment by MarlBurroW** [comment]
Seems to be related to #40

**Comment by MarlBurroW** [comment]
Found this from #40:
```blade
@if($image && $image->raw())
   @data($image)
        {{ $url }}
   @enddata
@endif
```
Seems a bit hacky and not very elegant, but does the job.

**Comment by stuartcusackie** [comment]
I'm currently going with:

```
@if(isset($image) && $image->raw())
  @data($image)
  @enddata
@endif
```

but today I realised that this still isn't enough. In some cases I have to check whether the file actually exists:

```
@if(isset($image) && $image->raw() && Storage::exists($image))
  @data($image)
  @enddata
@endif
```

**Comment by stuartcusackie** [comment]
Here's what I have gone with for now (not very well tested):

```
/**
 * helpers/statamic.php
 */

if(!function_exists('have_statamic_image')) {

	/**
	 * Check if a statamic image field is set and the
	 * file exists. Passing field by reference to 
	 * supress undefined variable warnings.
	 * 
	 * @param array | \Statamic\Field\Value $field
	 * @param String $disk
	 * @return String
	 */
	function have_statamic_image(&$field = null, $disk = 'public_images') {

		if(is_null($field)) {
			return false;
		}
		if(is_array($field)) {
			return isset($field['path']) && Storage::disk($disk)->exists($field['path']);
		}
		else if ($field instanceof \Statamic\Fields\Value) {
			return $field->raw() && Storage::disk($disk)->exists($field->raw());
		}

	}
}
```

```
@if(have_statamic_image($image))
	@data($image)
		{{-- Use the @glide directive here --}}
	@enddata
@endif
```

**Comment by edalzell** [comment]
Ya Statamic augments fields into a `Value` object even if there's nothing there, sorry. I don't like it either.

**Comment by edalzell** [comment]
@MarlBurroW what about an `@ifdata` directive, would that be better?

**Comment by MarlBurroW** [comment]
Yes, this will be slightly more straighfoward with this directive.
But the best for me would be to have just a null value in the $variable when `->raw()` is null, but I guess that involves changing the way statamic injects variables into the blade template, that's maybe not possible with the plugin API.

**Comment by edalzell** [comment]
> Yes, this will be slightly more straighfoward with this directive.
> But the best for me would be to have just a null value in the $variable when `->raw()` is null, but I guess that involves changing the way statamic injects variables into the blade template, that's maybe not possible with the plugin API.

It's not, that's up to Statamic. I can do the `@ifdata` directive, that's about it.

**Comment by edalzell** [comment]
Might have a solution for this if you're using Laravel 8: https://twitter.com/LukeDowning19/status/1397200594771787776

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
