### ISSUE TITLE
How to output links with the pagination directive?

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#48]
Hi, I'm just trying to figure out the pagination directive:

To add pagination links I would usually do something like:

`{{ $paginated->links() }}`

but I don't see how that's possible with this directive. I did a dump of the variables but couldn't see anything to do with pagination. 

Cheers!

**Comment by edalzell** [comment]
Let's see your template.

Here's mine:
```html
@collection('ordered_collection', ['limit'=> 1, 'paginate' => true])
    @dump($entry['paginate'])
@endcollection
```

<img width="437" alt="CleanShot 2021-05-23 at 17 31 39@2x" src="https://user-images.githubusercontent.com/6069653/119281993-c5caa480-bbec-11eb-9717-7afe3a8b39ec.png">

**Comment by stuartcusackie** [comment]
Sorry, your right. That data is available.

I think I was just confused by the fact that different variables get returned when using 'paginate' => true.

That's fixed now but one other small problem:

```
@collection('blog', ['sort="date:asc"', 'limit'=> 12, 'paginate' => true])

@if(!$entry['paginate']['total_items'])
  <p>There are no results</p>
@else
  @foreach($entry['entries'] as $entry)
    @data($entry)
      {{ $title }}
    @enddata
  @endforeach

  <a href="{{ $entry['paginate']['prev_page'] }}">⬅ Previous</a>
  <a href="{{ $entry['paginate']['next_page'] }}">Next ➡</a>
@endif

@endcollection
```

The above will produce an error because `@foreach($entry['entries'] as $entry)` overwrites `$entry['paginate']['prev_page']`. I have to change that loop to `@foreach($entry['entries'] as $entry2)`. 

Could the directive possible be updated to return $entries and $paginate as separate variables to avoid this? The variable names are a little confusing.

**Comment by edalzell** [comment]
> This is no big deal but perhaps the directive could be updated to return $entries and $paginate as separate variables to avoid this? I find the current variable names a little confusing.

Ya that's a bit tricky the way I have this architected at the moment. I'll see if there's anything I can do.

**Comment by edalzell** [comment]
Closing this in favour of the new issue I created: https://github.com/edalzell/statamic-blade/issues/50
