### ISSUE TITLE
Possible problem with @glide

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#49]
Hey, I've got a crashing server and the only clues I have are Glide exceptions. I'm not sure if it's a problem with this package, or with statamic, or with glide / guzzle. I've posted the full bug details on the Statamic github: https://github.com/statamic/cms/issues/3761

The error seems to eminate from calls to the @glide directive. It causes long running php requests that eventually break nginx. See the above issue for more detail and logs.

I've reinforced checks to make sure the asset file exists, but that did not solve it. Example:

```
@if(have_statamic_asset($image))
  @data($image)
    @glide(Storage::url($path), ['width' => 700, 'fm' => 'webp', 'bg' => '00ff00')])
      <img src="{{ $url }}" alt="{{ $alt }}" />
    @endglide
  @enddata
@endif
```

My helper method to check if the asset file actually exists:

```
/**
 * Check if a statamic asset array or value is set and 
 * that the file exists. Passing field by reference to 
 * suppress undefined variable warnings.
 * 
 * @param array | \Statamic\Field\Value $field
 * @param String $disk
 * @return Boolean
 */
function have_statamic_asset(&$field, $disk = 'public') {

  if(is_array($field)) {
    return isset($field['path']) && Storage::disk($disk)->exists($field['path']);
  }
  else if ($field instanceof \Statamic\Fields\Value) {
    return $field->raw() && Storage::disk($disk)->exists($field->raw());
  }

  return false;

}
```

Will update if I learn any more. Cheers.

**Comment by edalzell** [comment]
If you use Antlers do you get the same issue?

**Comment by stuartcusackie** [comment]
Unfortunately that would take a major reworking on my code. It's all blade component based.

The server hasn't crashed in a couple of days now so I will update if that happens again.

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
