### ISSUE TITLE
Feature request: @global directive to get global variables

### ISSUE THREAD

**Issue by miclf** [edalzell/statamic-blade#5]
As quickly discussed in the Statamic Discord earlier today, it would be nice to be able to get global variables via a Blade directive :)

I was thinking of something along the lines of:

```blade
{{-- Get the whole 'footer' global set, e.g. as a \Statamic\Globals\Variables object. --}}
@global('footer')

{{-- Get the value of the 'copyright' variable in the 'footer' global set. --}}
@global('footer:copyright')
```

The `set:variable` semantics seems more Statamic-ish to me, which might be especially helpful in projects that have several custom Blade directives that are unrelated to Statamic. I mean, since directives can’t be namespaced, having the ones related to Statamic use a Statamic-like syntax could serve as a hint of their Statamicness. This last sentence had a lot of Statamic words.

**Comment by edalzell** [comment]
done, both @globalset('footer')...@endglobalset and @globalset('footer', 'copyright') are supported.
