### ISSUE TITLE
"Undefined array key" error when retrieving all posts from a collection.

### ISSUE THREAD

**Issue by ElliotHouse** [edalzell/statamic-blade#52]
"Undefined array key" error when trying to retrieve all posts from a collection.

```
@collection('articles', ['orderBy' => 'desc']) 
  @if($entry == 0)
        <p>No Results</p>
  @else
        {{ $entry['title'] }}
  @endif
@endcollection
```

**Comment by edalzell** [comment]
You're missing a closing parentheses here `@collection('articles', ['orderBy' => 'desc'] ` <----

Should be `@collection('articles', ['orderBy' => 'desc'])`

**Comment by ElliotHouse** [comment]
That was my mistake in the example there. The error is still happening when using the if statement.

**Comment by edalzell** [comment]
Also, where did you get `orderBy` from? The `collection` tag uses `sort`.

<img width="755" alt="CleanShot 2021-06-30 at 20 30 31@2x" src="https://user-images.githubusercontent.com/6069653/124060502-07b3eb00-d9e2-11eb-9589-9068adf36ad1.png">

**Comment by ElliotHouse** [comment]
I seem to still be getting the issue "Undefined array key" when there are no posts in the collection. If I have a post in the collection it works otherwise the first field in the collection displays the error "Undefined array key".

For example when there are no posts in this collection I get the error Undefined array key "thumbnail". 

@collection('products', ['sort' => 'date:desc'])
	@if($entry == 0)
		<div class="col-span-2 text-center py-10">
			No Posts
		</div>
	@else
                <img src="{{ $entry['thumbnail'] }}">
	@endif
@endcollection

**Comment by grandpalacko** [comment]
@ElliotHouse If there are no entries in the collection, the `$entry` variable will be an array:

```
array:1 [▼
  "no_results" => true
]
```

So in your case the condition should be:

```
@if(!empty($entry['no_results'])
```

**Comment by edalzell** [comment]
Please try the above and re-open if still an issue, thanks.
