### ISSUE TITLE
@ray directive not working with augmentation enabled

### ISSUE THREAD

**Issue by marcorieser** [edalzell/statamic-blade#53]
I use the blade template engine and have `spatie/laravel-ray` installed on my statamic project. I can use `@ray($var)` in my view files and the output gets logged to the Ray app. 

I turned on augmentation by replacing the `Illuminate\View\ViewServiceProvider::class` with `Edalzell\Blade\Augmentation\AugmentationViewServiceProvider::class` and now my browser prints the `@ray($var)` directive call.

Spatie registers the Ray blade directive in `\Spatie\LaravelRay\RayServiceProvider::registerBladeDirectives` and returns early if `blade.compiler` is not present in the app:
```php
protected function registerBladeDirectives(): self
    {
        if (! $this->app->has('blade.compiler')) {
            return $this;
        }

        Blade::directive('ray', function ($expression) {
            return "<?php ray($expression); ?>";
        });

        return $this;
    }
```

The result of `$this->app->has('blade.compiler')` in  `RayServiceProvider::registerBladeDirectives` differs:

| Enabled ServiceProvider  | `ServiceProvider::registerBladeCompiler` called before `RayServiceProvider::registerBladeDirectives` | `$this->app->has('blade.compiler')` |
| ------------- | ------------- | ------------- |
| `Illuminate\View\ViewServiceProvider`  | `true`  | `true` |
| `Edalzell\Blade\Augmentation\AugmentationViewServiceProvider`  | `false`  | `false` |

Because the `AugmentationViewServiceProvider` is loaded after `RayServiceProvider::registerBladeDirectives` is called, the Ray directive gets not registered.

Is this something you can fix from your side?

**Comment by riasvdv** [comment]
In your composer.json you can disable the auto discover for Ray:

```json
"extra": {
        "laravel": {
            "dont-discover": [
                "spatie/laravel-ray"
            ]
        }
    },
```

And manually add the `\Spatie\LaravelRay\RayServiceProvider::class` to the providers in `config/app.php` below the AugmentationServiceProvider.

With the auto discovery there's sadly no way to influence the order in which the service providers are loaded.

**Comment by edalzell** [comment]
Thanks @riasvdv.

Try that @marcorieser.

**Comment by marcorieser** [comment]
@riasvdv thank you, i'll try that.
