### ISSUE TITLE
error while downloading

### ISSUE THREAD

**Issue by arfchmn** [edalzell/statamic-blade#54]
hello,

i have some problem when run composer in my project, you can see error message on attachment photo

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/43500645/125378228-92202580-e3b8-11eb-8d17-9275b3550677.png">

Thank you,

**Comment by edalzell** [comment]
What version of php are you running?

**Comment by arfchmn** [comment]
> What version of php are you running?

im running with PHP 7.2.22

**Comment by edalzell** [comment]
Need at least php 7.4
