### ISSUE TITLE
can't Automatic augmentation of Statamic values

### ISSUE THREAD

**Issue by arfchmn** [edalzell/statamic-blade#55]
hai edalzell,

sorry for my mistake about php version, i just update to php8.0 its work, 
but im still having problem after changing app.php for replace Illuminate\View\ViewServiceProvider::class, with \Edalzell\Blade\Augmentation\AugmentationViewServiceProvider,

when im command php artisan serve an error message comes, u can see on this screenshot

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/43500645/125405999-8cd7d080-e3e2-11eb-913c-b856201dbb29.png">

**Comment by grandpalacko** [comment]
@arfchmn You should replace `Illuminate\View\ViewServiceProvider::class` with the ServiceProvider's classname (you are missing `::class`):

```
\Edalzell\Blade\Augmentation\AugmentationViewServiceProvider::class
```

**Comment by edalzell** [comment]
Please try the above and re-open if still an issue
