### ISSUE TITLE
FR: add Bard directive

### ISSUE THREAD

**Issue by BobWez98** [edalzell/statamic-blade#60]
The about section of the repo states that the @bard directive is implemented but it's not working for me. It just outputs @bard($content) as a string.

**Comment by edalzell** [comment]
Ya looks like I wrote that and then didn't implement, sorry about that. I'll make this a feature request

**Comment by edalzell** [comment]
@BobWez98 what would you want it to output?

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
