### ISSUE TITLE
Nav field problem: Toggle value - Undefined Array key

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#65]
## Bug Description

For some reason the data returned for a  toggle field on a  'Nav Item' link is different to an 'Entry link'. I originally thought this was a core problem so you'll find more detail on my original issue: https://github.com/statamic/cms/issues/4290

## The Code

My toggle field is called **hide_from_header**. The below code will produce an error, but only for 'Nav Item' links.

```
@nav('main')
  @if(!$item['hide_from_header']->value())
    @if($item['children'])
       {{-- Output dropdown menu --}}
    @else
      {{-- Output simple nav item --}}
    @endif
  @endif
@endnav
```

## How to Reproduce

**The Problem**
1. Add a Toggle to a navigation blueprint.
2. Add a 'Nav Item' link (not an entry link) to the navigation.
3. **Don't change the toggle value**.
4. Click save
5. Note that the 'false' value DOES NOT get saved to yaml
6. Use the @nav blade directive and try to access $item['toggle_field']->value()
7. Error on front-end: `Undefined array key "toggle_field"`

**Workaround**
1. Add a Toggle to a navigation blueprint.
2. Add a 'Nav Item' link (not an entry) to the navigation.
3. **Switch the toggle on and back on again**.
4. Click save
5. Note that the 'false' value DOES get saved to yaml
6. My code works fine.

## Extra Detail
![image](https://user-images.githubusercontent.com/20210934/134084744-36990bc8-0f3d-4cf9-827c-60129fb07a41.png)

So I have to make sure that the non-entry Nav Item has the key defined in the yaml file, like so:

![image](https://user-images.githubusercontent.com/20210934/134084255-b549b269-54df-4a05-a45e-ec8cc8a3968f.png)

I don't need to do this on any of the Entry links in the navigation.

## Environment

Statamic 3.2.5 Solo
Laravel 8.61.0
PHP 8.0.10
edalzell/blade-directives 3.5

**Comment by edalzell** [comment]
Confirmed

**Comment by ryanmitchell** [comment]
Can you not do something like:
`@if(!optional($item['hide_from_header'])->value())`

**Comment by stuartcusackie** [comment]
Sure yeah, there are many ways to work around. I was just flagging this for inconsistency. I'm sure it's not the intended behaviour.

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
