### ISSUE TITLE
$data->jsonSerialize() causing slightly unexpected behavior in AugmentsValues.php

### ISSUE THREAD

**Issue by torian257x** [edalzell/statamic-blade#68]
big fan of your addon, saved me tons of time as I work with blade views.

I now noticed that my Enums from another great library ( https://github.com/BenSampo/laravel-enum ) always get "cast" to string

I first wrongly thought it's an issue with said library here https://github.com/BenSampo/laravel-enum/issues/229

but found the issue to be here:
https://github.com/edalzell/statamic-blade/blob/main/src/Concerns/AugmentsValues.php#L24

e.g. the enums implement JsonSerializable, and thus get converted to string.

I know I can implement my own version of 

`\Edalzell\Blade\Augmentation\AugmentationViewServiceProvider.php`

but.... I'd rather not as I am still new to statamic.

Is there another option or advice that you can give? 

as of now I guess the easiest is to go back to the laravel own `Illuminate\View\ViewServiceProvider::class,` in app.php
then fix all bugs that that will without a doubt cause.

But it would still leave something to be desired for, as `$data instanceof JsonSerializable` is just a bit too broad and will most likely cause a problem eventually?

Isn't there a bit more conservative check we could use? say... if it is in the namespace of statamic instead AND JsonSerializable? 

or is there a reasoning that that won't work and it _needs_ to be this way?

is as well related to https://github.com/edalzell/statamic-blade/issues/63

**Comment by edalzell** [comment]
@torian257x can you provide a working repo that shows this issue please?

**Comment by edalzell** [comment]
Thanks for the repo, I'll take a look.

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
