### ISSUE TITLE
IMHO 3.5.1 should be version 4.0 or at least 3.6

### ISSUE THREAD

**Issue by torian257x** [edalzell/statamic-blade#70]
this is a BIG breaking change

imho delete 3.5.1 and create v 4.0 or at least 3.6

otherwise your entire userbase will update to 3.5.1 and all will have a broken application

**Comment by edalzell** [comment]
Sorry this broke for you @torian257x, I'd recommend updating to Statamic 3.3 and using the native tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
