### ISSUE TITLE
How to access Bard fieldsets from a Statamic\Entries\Entry object

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#8]
Forgive me if I'm asking in the wrong place but it's very difficult to find any documentation on how to use Statamic objects with Blade. 

I'm trying to keep everything pure so that Statamic can be implemented into any existing Laravel apps. Example:

routes/web.php

```
Route::get('/blog/{postSlug}', function ($postSlug) {
    return view('blog.show', [
        'post' => Statamic\Facades\Entry::findBySlug($postSlug, 'posts')->toAugmentedArray()
     ]);
});
```

views/blog/show.blade.php
```
@bard($post['bard_field'])
    @include("partials/statamic/{$set['type']}", [ 'data' => $set['content']])
@endbard
```

This seems to work for the defaut Bard text items, as long as I have a partials/statamic/text.blade.php file created.

The problem I am having is for Bard sets / fieldsets. The fields are not being passed to my partial, e.g. partials/statamic/test_component.blade.php

Am I going about this entirely the wrong way or is there a limitation in the package?

**Comment by edalzell** [comment]
What does your data look like @stuartcusackie? Can you post an example?

**Comment by stuartcusackie** [comment]
Well if I dump the $set like so:

```
@bard($post->toAugmentedArray()['bard'])
    {{ var_dump($set) }}
    @include("partials/statamic/{$set['type']}", [ 'data' => $set['content']])
@endbard
```

Then I will get output like so:

```
/home/vagrant/website.ie/storage/framework/views/5578389d564c6366cb9864d7be65cd668bab864b.php:4:
array (size=2)
  'type' => string 'text' (length=4)
  'content' => string '<p>Text block content</p>' (length=151)
Text block content

/home/vagrant/website.ie/storage/framework/views/5578389d564c6366cb9864d7be65cd668bab864b.php:4:
array (size=2)
  'type' => string 'test_component' (length=14)
  'content' => string 'Custom set text' (length=31)
Custom set text

/home/vagrant/website.ie/storage/framework/views/5578389d564c6366cb9864d7be65cd668bab864b.php:4:
array (size=2)
  'type' => string 'text' (length=4)
  'content' => string '<h2>More text block content</h2><p>Test</p>' (length=183)
## More text block content
Test
```

So I thought that maybe I need a View Model to prepare the data of my custom set but it doesn't seem to trigger anything. Do I need to trigger the cascade or something like that before passing the Entry object to my view?

**Comment by edalzell** [comment]
Closing in favour of #6
